import { test,expect } from '@playwright/test';

test('loads Melbourne and drives forward through braking, pause, and automatic platform-camera checks',async({page})=>{
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
  page.on('console',message=>{if(message.type()==='error')errors.push(message.text());});
  await page.goto('/');
  const start=page.getByRole('button',{name:'Take the driver’s seat'});
  await expect(start).toBeEnabled({timeout:60000});
  await expect(page.locator('#viewport canvas')).toHaveAttribute('data-renderer-backend','WebGPU');
  await page.screenshot({path:'artifacts/01-city-menu.png'});
  await start.click();
  await expect(page.locator('#driving-hud')).toBeVisible();
  const canvas=page.locator('#viewport canvas');
  await expect(canvas).toHaveAttribute('data-camera-view','door-check');
  await expect(canvas).toHaveAttribute('data-camera-input','disabled');
  await expect(page.getByRole('button',{name:'Outside view'})).toHaveCount(0);
  await page.keyboard.press('w');await page.waitForTimeout(500);
  expect(await page.evaluate(()=>(window as any).__RAIL_EXPLORER__.state().speed)).toBe(0);
  await page.keyboard.press('d');await page.keyboard.press('w');await page.keyboard.press('w');
  await expect.poll(()=>page.evaluate(()=>(window as any).__RAIL_EXPLORER__.state().speed)).toBeGreaterThan(.5);
  await page.screenshot({path:'artifacts/02-cab-departure.png'});
  await expect(canvas).toHaveAttribute('data-camera-view','cab');
  await page.keyboard.press('c');await expect(canvas).toHaveAttribute('data-camera-view','cab');
  await page.mouse.move(630,300);await page.mouse.down();await page.mouse.move(710,320);await page.mouse.up();
  await expect.poll(()=>canvas.evaluate(el=>JSON.parse((el as HTMLCanvasElement).dataset.cameraLook!).yaw)).toBe(0);
  await page.mouse.dblclick(630,300);
  await expect.poll(()=>canvas.evaluate(el=>JSON.parse((el as HTMLCanvasElement).dataset.cameraLook!).yaw)).toBe(0);
  await page.keyboard.press('Escape');const paused=await page.evaluate(()=>(window as any).__RAIL_EXPLORER__.state());
  await page.waitForTimeout(250);expect(await page.evaluate(()=>(window as any).__RAIL_EXPLORER__.state().distance)).toBe(paused.distance);
  await page.getByRole('button',{name:'Resume service'}).click();
  await page.keyboard.press('Space');
  await expect.poll(()=>page.evaluate(()=>(window as any).__RAIL_EXPLORER__.state().speed),{timeout:15000}).toBe(0);
  await page.evaluate(()=>(window as any).__RAIL_EXPLORER__.scenario('tunnel'));
  await page.waitForTimeout(1000);await page.screenshot({path:'artifacts/04-tunnel.png'});
  await page.keyboard.press('m');await expect(page.getByRole('img',{name:'City Loop route with five station stops'})).toBeVisible();
  await page.screenshot({path:'artifacts/05-map.png'});
  await page.getByRole('button',{name:'Close panel'}).click();
  await page.evaluate(()=>(window as any).__RAIL_EXPLORER__.scenario('platform'));
  await expect(page.locator('#station-instruction')).toHaveText('Open doors');
  await page.keyboard.press('d');await expect(page.locator('#doors-label')).toContainText('Boarding');
  await expect(canvas).toHaveAttribute('data-camera-view','door-check');
  await expect(canvas).toHaveAttribute('data-camera-input','enabled');
  const doorCamera=JSON.parse((await canvas.getAttribute('data-camera-look'))!);
  await page.mouse.move(630,300);await page.mouse.down();await page.mouse.move(750,330);await page.mouse.up();
  await expect.poll(()=>canvas.evaluate(el=>JSON.parse((el as HTMLCanvasElement).dataset.cameraLook!).yaw)).not.toBe(0);
  const movedDoorCamera=JSON.parse((await canvas.getAttribute('data-camera-look'))!);
  expect(movedDoorCamera.position).toEqual(doorCamera.position);
  await page.mouse.dblclick(630,300);
  await expect.poll(()=>canvas.evaluate(el=>JSON.parse((el as HTMLCanvasElement).dataset.cameraLook!).yaw)).toBe(0);
  await page.screenshot({path:'artifacts/08-underground-platform.png'});
  await expect(page.locator('#doors-label')).toHaveText('Close doors',{timeout:12000});
  await page.keyboard.press('d');await expect(page.locator('#station-name')).toHaveText('Parliament');
  await expect(canvas).toHaveAttribute('data-camera-view','cab');
  await expect(canvas).toHaveAttribute('data-camera-input','disabled');
  await expect.poll(()=>canvas.evaluate(el=>JSON.parse((el as HTMLCanvasElement).dataset.cameraLook!).yaw)).toBe(0);
  await page.keyboard.press('Escape');await page.reload();
  await expect(page.getByRole('button',{name:'Continue saved service'})).toBeVisible();
  await expect(page.getByRole('button',{name:'Take the driver’s seat'})).toBeEnabled({timeout:60000});
  await page.getByRole('button',{name:'Continue saved service'}).click();await expect(page.locator('#driving-hud')).toBeVisible();
  console.log('RENDER_METRICS',await page.evaluate(()=>(window as any).__RAIL_EXPLORER__.metrics()));
  expect(errors).toEqual([]);
});

test('a narrow window scales the complete wide game without rearranging the desk',async({page})=>{
  await page.setViewportSize({width:600,height:850});await page.goto('/');
  await expect(page.getByRole('button',{name:'Take the driver’s seat'})).toBeEnabled({timeout:60000});
  await page.screenshot({path:'artifacts/06-narrow-menu.png'});
  await page.getByRole('button',{name:'Take the driver’s seat'}).click();
  await expect(page.locator('#driving-hud')).toBeVisible();
  await expect(page.locator('#welcome')).toBeHidden();
  await page.screenshot({path:'artifacts/07-narrow-cab.png'});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBe(600);
  const stage=await page.locator('#app').evaluate(element=>({width:(element as HTMLElement).offsetWidth,height:(element as HTMLElement).offsetHeight,visibleWidth:element.getBoundingClientRect().width,visibleHeight:element.getBoundingClientRect().height}));
  expect(stage.width).toBe(1280);expect(stage.height).toBe(720);
  expect(stage.visibleWidth).toBeCloseTo(600);expect(stage.visibleWidth/stage.visibleHeight).toBeCloseTo(16/9);
  await expect(page.getByRole('complementary',{name:'Left cab panel'})).toBeVisible();
  await expect(page.getByRole('complementary',{name:'Right cab panel'})).toBeVisible();
});
